title: Dongzhi Luo's Homepage
page-top-title: Dongzhi Luo
top-section-bg-text: Maybe this is a interesting soul.
home-subtitle: Dongzhi Luo  |  罗冬致
copyright-text: '&copy; Dongzhi Luo 2025-2027. All Rights Reserved.'
